meta_product_name: "What The Food"
meta_title: "What The Food | LeWagon #830"
meta_description: "What can you cook with ingredients in your fridge?"
meta_image: "cover.png" # should exist in `app/assets/images/`
